site_name: Software Development Notes 
nav:
  - Home: index.md
  - Homeworks: 
    - Assignment 0: Homework/hwa0.md
    - Assignment 1: Homework/hwa1.md
    - Assignment 2: Homework/hwa2.md
    - Assignment 3: Homework/hwa3.md
    - Assignment 4: Homework/hwa4.md
    - Assignment 5: Homework/hwa5.md
    - Assignment 6: Homework/hwa6.md
    - Assignment 7: Homework/hwa7.md
    - Assignment 8: Homework/hwa8.md
    - Assignment 10: Homework/hwa10.md
    - Assignment 11: Homework/hwa11.md
    - Assignment 12: Homework/hwa12.md
  - API Reference: 
    - bifurcation: API/bifurcation.md
    - binary: API/binary.md
    - files: API/files.md
    - interleave: API/interleave.md

theme: material
plugins:
  - mkdocstrings:
      handlers:
          python:
            options:
              docstring_style: google 
              docstring_section_style: table
              show_docstring_functions: true
              show_docstring_modules: true
              show_docstring_description: false 


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
